### ISSUE TITLE
Automatic import on module update

### ISSUE THREAD

**Issue by sylvain-garancher** [syleam/stock_scanner#10]
I just tested and validated v8 migration, thanks to @damdam-s and @lmignon for the great work they did.

I also added an automatic import feature, to create/update the scenarios, as any other data file, during module install/update.
The UUID is now used as an XML ID, so deletion of removed scenarios/steps/transitions is now automatically done. We can imagine drop UUIDs later, and use readable XML IDs instead :)

@damdam-s and @lmignon : Can you review and comment this, before I propose the module to OCA ?
Especially the monkey patch, I don't like that, but didn't found any other way to reach this goal.
Do you think about any improvement on the scenario manifest format ?

**Comment by damdam-s** [comment]
@sylvain-garancher Great to have an automatic import behaviour. No need to run another command anymore to update scenario :sunglasses: 
For the monkey patch, I don't see another way to do it so :+1: 

For OCA proposal, I think travis will be red because of PEP8 (line too long).

Thanks

**Comment by lmignon** [comment]
@damdam-s @sylvain-garancher for OCA I've fixed PEP-8 issues, created somes unitests and created the travis file. Before your changes, travis was green on our gtihub account (https://travis-ci.org/acsone/stock_scanner). @sylvain-garancher if you register your github account on travis, the module will be validated with the same rules as the ones for  OCA

**Comment by lmignon** [comment]
@damdam-s @sylvain-garancher oups, it's not possible to validate the sources by using OCA tools since the module at the root of the repository.  (should be '/stock_scanner/*') But I've a branch with the expected structure and you can see the results of the last changes here https://travis-ci.org/acsone/stock_scanner/builds/88289203. With some new pep8 issues...
```
======== Testing test_flake8 ========
stock_scanner/load_scenario.py:4:80: E501 line too long (92 > 79 characters)
stock_scanner/load_scenario.py:11:80: E501 line too long (80 > 79 characters)
stock_scanner/load_scenario.py:67:80: E501 line too long (81 > 79 characters)
stock_scanner/load_scenario.py:114:80: E501 line too long (129 > 79 characters)
stock_scanner/load_scenario.py:130:80: E501 line too long (83 > 79 characters)
stock_scanner/load_scenario.py:150:80: E501 line too long (130 > 79 characters)
stock_scanner/load_scenario.py:164:80: E501 line too long (148 > 79 characters)
stock_scanner/load_scenario.py:167:80: E501 line too long (125 > 79 characters)
stock_scanner/load_scenario.py:180:80: E501 line too long (82 > 79 characters)
stock_scanner/load_scenario.py:184:80: E501 line too long (124 > 79 characters)
stock_scanner/load_scenario.py:186:80: E501 line too long (89 > 79 characters)
======== Testing test_pylint ========
```

**Comment by sylvain-garancher** [comment]
Sorry, my flake8 configuration was ignoring the E501 error (line too long).
I fixed that :)

**Comment by lmignon** [comment]
@sylvain-garancher Green :smile: https://travis-ci.org/acsone/stock_scanner/builds/88290775

**Comment by sylvain-garancher** [comment]
I fixed the export script to generate a `Scenario_Name.scenario` file instead `scenario.xml`, and updated the README file.
I still need to add a migration script to create XML IDs for existing scenarios in database.

I think about removing the `uuid` field, and use (normalized) `name` instead, for XML IDs, do you have a better idea ?

**Comment by lmignon** [comment]
@sylvain-garancher 
> I think about removing the uuid field, and use (normalized) name instead, for XML IDs,
:+1:

**Comment by laetitia-gangloff** [comment]
Great functionality !
Thanks @sylvain-garancher

**Comment by lmignon** [comment]
@sylvain-garancher IMO This module is ready to be proposed to OCA. The import of scenarios is a great improvement!

**Comment by sylvain-garancher** [comment]
Not exactly ready, demo scenarios are not fully migrated to v8 :D

I just created the https://github.com/syleam/stock_scanner/tree/8.0-remove_uuids branch, to replace UUIDs by XML IDs (by default based on the name).
In this branch :
- The "reference_res_id" field, which contained UUIDs, has been removed
- The import and export scripts are updated to reflect this change : When no XML ID exists on export, it's generated from the scenario and step/transition name
- Demo scenario IDs (and, thus, python file names) are now readable, instead of UUIDs
- Login and Logout scenarios are exported in scenario directories and removed from the XML data file

I also added a check for groups, to allow XML IDs in the "group_ids" node in scenario files, in addition to group names.

**Comment by lmignon** [comment]
@sylvain-garancher IMO the login/logout should stay as usual XML data to be easily overridable/extendable. Moreover these scenarii was defined with a noupdate="1".

**Comment by sylvain-garancher** [comment]
You are right, I missed the noupdate attribute.
This is fixed now, we can put `<scenario noupdate="1">` to keep this behaviour.

As scenarios now use XML IDs, overriding values is as easy as modifying any other value.
You can override a scenario from another module using CSV, XML or scenario file, including modifying existing values, adding or deleting new steps/transitions, etc.

**Comment by lmignon** [comment]
@sylvain-garancher By default login/logout should be ```<field name="active" eval="False"/>```
In the same time you should move all the code under a stock_scanner directory to enable tests by travis... I've added some basic tests and if travis was enabled  you would have seen that your changes breaks the existing code  ;-)

**Comment by sylvain-garancher** [comment]
Login and Logout are `active=False` actually (in the scenario file, and in my local database).

I planned to move into a `stock_scanner` subdirectory when making the OCA PR.
I run the tests on my local instance (without Travis), and all is OK here. What test does fail ?

**Comment by lmignon** [comment]
@sylvain-garancher My bad. haven't seen the active='false' in the scenario file and therefore expected an error when running tests.
